{% set name = "opentelemetry-instrumentation-starlette" %}
{% set version = "0.29b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-starlette-{{ version }}.tar.gz
  sha256: 5224700c43eabb6650e170b754cd0c173dd6b19e738d388290401e7d3d672912

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.29b0
    - opentelemetry-instrumentation-asgi ==0.29b0
    - opentelemetry-semantic-conventions ==0.29b0
    - opentelemetry-util-http ==0.29b0
    - python >=3.6
    # - starlette ~=0.13.0
    # - requests ~=2.23.0
    # - opentelemetry-test ==0.24b0
    # - starlette ~=0.13.0
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.26b1
    # - starlette ~=0.13.0
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.27b0
    # - starlette ~=0.13.0
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.28b0
    # - starlette ~=0.13.0
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.28b1
    # - starlette ~=0.13.0
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.29b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-starlette
  summary: OpenTelemetry Starlette Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
